name: MinecraftNoticePlugin
version: 1.0.3
main: org.megoru.ru.Main
description: Уведомляет о заходах на сервер в Discord через WebHook
author: megoRU
website: https://megoru.ru
load: POSTWORLD
api-version: '1.13'